Verify theme was downloaded properly.
Signed-off-by: Matt Bagley <firstlife22@gmail.com>

diff --git a/wptool b/wptool
--- a/wptool
+++ b/wptool
@@ -379,10 +379,25 @@ function wptheme() {
     echo -e "\nAvailable themes:\n"
     ls -F $folder |grep "/"|grep -v "^\."|sed "s|^\(.*\)/|\t\1|" #ls -A is overwritten by default $LS_OPTIONS in alias
   elif [[ $1 == "fresh" ]]; then
+    if ! [[ -f "$folder/twentytwelve.1.1.zip" ]] ; then 
     wget --no-check-certificate -P $folder https://wordpress.org/extend/themes/download/twentytwelve.1.1.zip && echo "Downloaded twentytwelve.1.1.zip..." || {
       echo Unable to download twentytwelve.1.1.zip!
       return 9
     }
+    fi
+    # check if file was properly downloaded and not corrupt
+    echo "Verifying downloaded file..."
+    unzip -t "$folder/twentytwelve.1.1.zip" > /dev/null
+    zip_exit_code=$?
+    if [[ $zip_exit_code -ne 0 ]] ; then
+      echo -e "\nError: Downloaded file was corrupt: unzip test gave error code $zip_exit_code"
+      rm -f "$folder/twentytwelve.1.1.zip"
+      echo -e "Removed corrupt file: $folder/twentytwelve.1.1.zip"
+      echo "Try running the command again...."
+      return 9
+    else
+      echo "twentytwelve.1.1.zip appears to be okay."
+    fi
     temp=$(now)
     [[ -d $folder/twentytwelve ]] && mv $folder/twentytwelve $folder/twentytwelve_$temp && echo "Moved old twentytwelve files to twentytwelve_$temp..."
     unzip $folder/twentytwelve.1.1.zip -d $folder >/dev/null && echo "Extracted new twentytwelve files..." || {
